# Generated by Django 4.2.7 on 2023-11-19 17:42

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdr',
            name='called_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер вызываемого абонента'),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='calling_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер вызывающего абонента'),
        ),
    ]
