# Generated by Django 4.2.7 on 2023-11-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_cdr_called_number_alter_cdr_calling_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdr',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'success'), ('missed', 'missed'), ('declined', 'declined')], null=True, verbose_name='Статус'),
        ),
    ]
