# Generated by Django 4.2.7 on 2023-11-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_cdr_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdr',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('missed', 'missed'), ('declined', 'declined')], verbose_name='Статус'),
        ),
    ]
