# Generated by Django 4.2.7 on 2023-11-20 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_cdr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdr',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
